# Generated by Django 4.2.5 on 2024-01-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, null=True)),
                ('lastname', models.CharField(blank=True, null=True)),
                ('username', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('address2', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, null=True)),
                ('same_address', models.CharField(blank=True, null=True)),
                ('save_info', models.CharField(blank=True, null=True)),
                ('cc_name', models.CharField(blank=True, null=True)),
                ('cc_number', models.CharField(blank=True, null=True)),
                ('cc_expiration', models.CharField(blank=True, null=True)),
                ('cc_cvv', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecapp.cartmodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_carts', to='ecapp.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BuyDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_buys', to='ecapp.billmodel')),
            ],
        ),
    ]
