# Generated by Django 4.2.5 on 2024-01-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyDetailModel',
            new_name='BuyItemModel',
        ),
    ]
