# Generated by Django 4.2.5 on 2023-12-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(blank=True, default=1, null=True, upload_to=''),
        ),
    ]
