# Generated by Django 4.2.5 on 2023-12-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0002_itemmodel_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='title',
            field=models.CharField(blank=True, default=1, null=True),
        ),
    ]
