# Generated by Django 4.2.5 on 2024-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0002_promocodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodemodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
