# Generated by Django 4.2.5 on 2024-01-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0002_buydetailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetailmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='buydetailmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buydetailmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='buydetailmodel',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_buy', to='ecapp.cartmodel'),
        ),
    ]
