# Generated by Django 4.2.5 on 2024-01-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0003_remove_buydetailmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buydetailmodel',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecapp.cartmodel'),
        ),
    ]
