# Generated by Django 4.2.5 on 2023-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0004_alter_itemmodel_item_image_alter_itemmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
