# Generated by Django 4.2.5 on 2024-01-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0004_alter_buydetailmodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetailmodel',
            name='cart',
        ),
        migrations.AddField(
            model_name='buydetailmodel',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_buys', to='ecapp.billmodel'),
        ),
        migrations.AddField(
            model_name='buydetailmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buydetailmodel',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buydetailmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
