# Generated by Django 4.2.5 on 2023-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0005_itemmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('address2', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, null=True)),
                ('shipping', models.CharField(blank=True, null=True)),
                ('save', models.CharField(blank=True, null=True)),
                ('name_on_card', models.CharField(blank=True, null=True)),
                ('credit_card_number', models.CharField(blank=True, null=True)),
                ('expiration', models.CharField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
