# Generated by Django 4.2.5 on 2023-12-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0006_cartmodel_cartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecapp.cartmodel'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_carts', to='ecapp.itemmodel'),
        ),
    ]
