# Generated by Django 4.2.5 on 2023-12-31 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0006_billmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billmodel',
            old_name='credit_card_number',
            new_name='cc_cvv',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='cvv',
            new_name='cc_expiration',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='expiration',
            new_name='cc_name',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='first_name',
            new_name='cc_number',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='last_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='name_on_card',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='save',
            new_name='same_address',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='shipping',
            new_name='save_info',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
