# Generated by Django 4.2.5 on 2023-12-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0007_rename_credit_card_number_billmodel_cc_cvv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billmodel',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
