# Generated by Django 4.2.5 on 2023-12-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecapp', '0008_rename_firstname_billmodel_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='title',
        ),
    ]
