[tool.black]
line_length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true

[tool.mypy.plugins.yaml]
ignore_missing_imports = true